### ISSUE TITLE
Method protected, Excel::export(...) does not work

### ISSUE THREAD

**Issue by squiaios** [Maatwebsite/laravel-excel-docs#1]
Hello,

In your guide, we can use export method, but this one is protected :)
https://laravel-excel.maatwebsite.nl/3.0/getting-started/installation.html#via-the-facade

**Comment by patrickbrouwers** [comment]
It’s a facade, so you can just call the method

**Comment by patrickbrouwers** [comment]
Thanks examples are fixed 👍
