### ISSUE TITLE
The document format is not covered for importing

### ISSUE THREAD

**Issue by kurucu** [Maatwebsite/laravel-excel-docs#20]
The documentation does not cover whether different spreadsheet formats can be used for Imports.

If they can be, it should mention whether this is automatic, or otherwise how the developer specifies the file format type.

There is an implication that it's Excel 2007+ only (xlsx), only because they are the only extension types used in the examples.

**Comment by patrickbrouwers** [comment]
It might not be overly explicit, but we have a note about it: https://laravel-excel.maatwebsite.nl/3.1/imports/basics.html#specifying-a-reader-type 

Also you can refer to https://github.com/Maatwebsite/Laravel-Excel/blob/3.1/config/excel.php#L75

**Comment by patrickbrouwers** [comment]
Added a page with a list of import formats

**Comment by kurucu** [comment]
Thanks. I did some more reading and realised it's actually very powerful, but I had to dig to find this out. I'll add a pull request next time! Thanks for the quick turnaround.

**Comment by patrickbrouwers** [comment]
Great!
